23 create placeholder profile edit calls
FantasyEsports-ACC/Fantasy-Esports pull request #30
Opened 2024-10-14 23:24 UTC by soup-scott

- Created directory api/updateProfile within src/app
- Added file route.ts with skeleton api handlers

2024-10-14 23:46 UTC, SamShrubo approved these changes, later dismissed

2024-10-15 18:51 UTC, IMMZEK requested changes
Once that those changes are removed I can approve.

2024-10-15 18:51 UTC, IMMZEK commented on .github/ISSUE_TEMPLATE/BackEnd-feature-template.md
I dont believe you should change our issue template, since we use that to create tickets.

2024-10-15 18:56 UTC, SamShrubo commented on .github/ISSUE_TEMPLATE/BackEnd-feature-template.md
it is the same template as was in main so I believe it was originally cloned from there, dev doesn't currently have the issue templates that main does

2024-10-16 00:04 UTC, SamShrubo approved these changes, later dismissed

2024-10-16 00:04 UTC, IMMZEK approved these changes
LGTM

2024-10-16 00:04 UTC, IMMZEK approved these changes

2024-10-16 00:05 UTC, SamShrubo approved these changes

2024-10-16 00:06 UTC, SamShrubo submitted a review, later dismissed

2024-10-16 00:06 UTC, IMMZEK approved these changes

2024-10-16 00:06 UTC, IMMZEK submitted a review, later dismissed

2024-10-16 00:12 UTC, merged