Added route to API for changing profile pic
FantasyEsports-ACC/Fantasy-Esports pull request #34
Opened 2024-10-15 18:45 UTC by RuthavSadali

Added the route to the API for changing the profile pic. Currently, route.ts is filled with placeholder text.

2024-10-15 18:53 UTC, SamShrubo requested changes
please change the merge destination from main to dev, and set cesar and I as the required approvers in the top right

2024-10-16 00:00 UTC, SamShrubo submitted a review, later dismissed

2024-10-16 00:08 UTC, IMMZEK approved these changes, later dismissed

2024-10-16 00:09 UTC, IMMZEK approved these changes

2024-10-16 00:09 UTC, SamShrubo approved these changes

2024-10-16 00:09 UTC, IMMZEK approved these changes

2024-10-16 00:09 UTC, SamShrubo approved these changes

2024-10-16 00:12 UTC, merged